---
title: "Shrub-Lizard Data Method 2 Test Repo"
author: "Mario"
date: '2021-03-31'
output: html_document
---
###The following is a test repo to connect the density of shrub individuals within the Carrizo Plain National Monument to the data collected from the Lizard Telemetry Project.

```{r}
library(data.table)
library(sp)
library(rgdal)
library(ggplot2)
```
```{r}
shrub_dat = fread("Untitled_layer.csv")
shrub_dat = as.data.table(shrub_dat)
```

```{r}
coordinates(shrub_dat) = c("x", "y")
crs.geo1 = CRS("+proj=longlat")
proj4string(shrub_dat) = crs.geo1

plot(shrub_dat, pch = 20, col = "steelblue")
```
```{r}
carrizo = readOGR(dsn = path.expand("mygeodata"),layer = "Untitled_Project_1-polygon")
```
```{r}
plot(carrizo)
points(shrub_dat, pch = 20, col = "orange")
```
```{r}
library(ggmap)
shrubs <- read.csv("Shrubs.csv")
lizard <- read.csv("Lizards.csv")

register_google(key="AIzaSyBurG6FR6I4uc_nRUr6TY118dCsnM0tsiE")
carrizo <- get_map(location = c(lon = -119.6287, lat = 35.11941), zoom = 16, maptype = "satellite")
carrizo
site.wide.map <- ggmap(carrizo)
site.wide.map <- site.wide.map +
  geom_point(data=shrubs, aes(x=X, y=Y, color = Site), alpha = 1, size =0.1, shape = 0, color = "green", show.legend = FALSE) +
  labs(x = "longitude", y = "latitude") + theme(axis.title.x = element_blank()) + theme(axis.title.y = element_blank())
site.wide.map <- site.wide.map +
  geom_point(data=lizard, aes(x=Lng, y=Lat, color = Site), alpha = 1, size =0.1, shape = 0, color = "red", show.legend = FALSE) +
  labs(x = "longitude", y = "latitude") + theme(axis.title.x = element_blank()) + theme(axis.title.y = element_blank())
site.wide.map
##Generating the map with the datasets is easy. Finding the number of individuals per area is thr tricky part now.
```
